### PR TITLE
Fix update default group settings

### PR DESCRIPTION
**Pull request by carrk-osu**
- Added new Method called "DisableAddingGuests" which will automatically set a new team's "AllowToAddGuests" to `$False`

### CODE REVIEW

**Comment by carrk-osu** [comment]
- Using a **dev** deployment in the Azure portal I was able to successfully generate a new team:
```PowerShell
{
  "Visibility": "Private",
  "DisplayName": "Teams API Test - Group Settings 2",
  "rowKey": "8c5da5fd-bc9d-4da2-8db2-7c18ffc7a999",
  "partitionKey": "TeamsLog",
  "Mail": "TeamsAPITestGroupSettings21138445820@OregonStateUniversity.onmicrosoft.com",
  "Status": "SUCCESS",
  "Description": "Testing Group Settings, expected that adding guests is false",
  "ID": "9ee70523-366d-4c77-b5fc-92e808366749",
  "TicketID": "12345678"
}
```

- Confirmed (using graph explorer) that the proper setting was set:

```PowerShell
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#groupSettings",
    "value": [
        {
            "id": "500fd7c4-8222-4f21-9542-430d5ad5f2b3",
            "displayName": "Group.Unified.Guest",
            "templateId": "08d542b9-071f-4e16-94b0-74abb372e3d9",
            "values": [
                {
                    "name": "AllowToAddGuests",
                    "value": "false"
                }
            ]
        }
    ]
}
```

**Comment by carrk-osu** [comment]
- We're currently looking at a "squash and merge" So we've only got one single commit to master.
- **Once this is merged, it will AUTOMATICALLY update our TeamsCreate Azure App Function**

**Review by zojoncj — APPROVED** [review]
Looks good to me.

**Comment by carrk-osu** [comment]
Automated TDx process tested in ticket:
Request for Team in Microsoft Teams
Service Request #16020560

- [X] Confirmed that Azure auto-updated with most current change
- [X] Reviewed Azure function monitoring log and confirmed that the team object was created as expected (no errors)
- [X] Confirmed that Teams's attributes were as expected (checked via azure Storage Explorer, Graph Explorer)
- [X] Confirmed TDx workflow completed successfully
- [X] Confirmed that the timed GAL changes on the teams object succeeded
- [X] Removed Test Team and its related resources

**Pull request merged**
